### PR TITLE
Updated to include message from alert

### PR DESCRIPTION
**Pull request by sronanrh**
Updated to include message from commit in both initial jq and column.

### CODE REVIEW

**Comment by dcritch** [comment]
I took a look. This did the trick:
echo $alerts | jq -r '. | "\(.severity)\t\(.alert)\t\(.namespace)\t\(.instance)\t\(.message)"' | column  -t -s $'\t' -N "SEVERITY,ALERT,NAMESPACE,INSTANCE,MESSAGE"

Much nicer looking. However it will still wrap. How do you feel about '-T 5' to truncate that column if necessary?

**Comment by sronanrh** [comment]
Does that actually work for you? When I run that I get errors - 

checks/alertmanager: line 9: unexpected EOF while looking for matching `)'
checks/alertmanager: line 16: syntax error: unexpected end of file

**Comment by dcritch** [comment]
That was just my CLI test, but the line in the script would be:
```
    ALERTS=$(echo "${alerts}" | jq -r '. | "\(.severity)\t\(.alert)\t\(.namespace)\t\(.instance)\t\(.message)"' | column -t -s $'\t' -N "SEVERITY,ALERT,NAMESPACE,INSTANCE,MESSAGE")
```

It returns:
```
Alerts currently firing:
SEVERITY  ALERT                               NAMESPACE                  INSTANCE         MESSAGE
warning   AlertmanagerReceiversNotConfigured  null                       null             Alerts are not configured to be sent to a notification system, meaning that you may not be notified in a timely fashion when important failures occur. Check the OpenShift documentation to learn how to configure notifications with Alertmanager.
critical  CannotRetrieveUpdates               openshift-cluster-version  10.19.33.1:9099  Cluster version operator has not retrieved updates in 21h 12m 20s. Failure reason VersionNotFound .  For more information refer to https://console-openshift-console.apps.clus3b.t5g.lab.eng.bos.redhat.com/settings/cluster/.

Total issues found: 1
```

There is the  `-T 5` arg that will truncate, but since we store it as a variable, it looks to always cut off, no matter how wide your terminal is:
```
$ ./openshift-checks.sh -s checks/alertmanager  
Using admin context
Alerts currently firing:
SEVERITY  ALERT                               NAMESPACE                  INSTANCE         MESSAGE
warning   AlertmanagerReceiversNotConfigured  null                       null             Alerts 
warning   KubeClientCertificateExpiration     default                    10.19.33.3:6443  A clien
warning   KubeClientCertificateExpiration     default                    10.19.33.1:6443  A clien
warning   KubeClientCertificateExpiration     default                    10.19.33.2:6443  A clien
critical  CannotRetrieveUpdates               openshift-cluster-version  10.19.33.1:9099  Cluster

Total issues found: 1

```
So on the one hand, it would be nice to have it properly truncate, but on the other, it might not be worth the hassle and with the `-s` it looks much better.

What do you think @ptrnull and @e-minguez ?

**Comment by e-minguez** [comment]
> That was just my CLI test, but the line in the script would be:
> 
> ```
>     ALERTS=$(echo "${alerts}" | jq -r '. | "\(.severity)\t\(.alert)\t\(.namespace)\t\(.instance)\t\(.message)"' | column -t -s $'\t' -N "SEVERITY,ALERT,NAMESPACE,INSTANCE,MESSAGE")
> ```
> 
> It returns:
> 
> ```
> Alerts currently firing:
> SEVERITY  ALERT                               NAMESPACE                  INSTANCE         MESSAGE
> warning   AlertmanagerReceiversNotConfigured  null                       null             Alerts are not configured to be sent to a notification system, meaning that you may not be notified in a timely fashion when important failures occur. Check the OpenShift documentation to learn how to configure notifications with Alertmanager.
> critical  CannotRetrieveUpdates               openshift-cluster-version  10.19.33.1:9099  Cluster version operator has not retrieved updates in 21h 12m 20s. Failure reason VersionNotFound .  For more information refer to https://console-openshift-console.apps.clus3b.t5g.lab.eng.bos.redhat.com/settings/cluster/.
> 
> Total issues found: 1
> ```
> 
> EDIT: github doesn't wrap it, but your shell will.
> 
> There is the `-T 5` arg that will truncate, but since we store it as a variable, it looks to always cut off, no matter how wide your terminal is:
> 
> ```
> $ ./openshift-checks.sh -s checks/alertmanager  
> Using admin context
> Alerts currently firing:
> SEVERITY  ALERT                               NAMESPACE                  INSTANCE         MESSAGE
> warning   AlertmanagerReceiversNotConfigured  null                       null             Alerts 
> warning   KubeClientCertificateExpiration     default                    10.19.33.3:6443  A clien
> warning   KubeClientCertificateExpiration     default                    10.19.33.1:6443  A clien
> warning   KubeClientCertificateExpiration     default                    10.19.33.2:6443  A clien
> critical  CannotRetrieveUpdates               openshift-cluster-version  10.19.33.1:9099  Cluster
> 
> Total issues found: 1
> ```
> 
> So on the one hand, it would be nice to have it properly truncate, but on the other, it might not be worth the hassle and with the `-s` it looks much better.
> 
> What do you think @ptrnull and @e-minguez ?

I'm leaning towards having the full message.

**Comment by sronanrh** [comment]
Thanks, for some reason it was not working for me on the command line either. I think we need to keep the full message, otherwise we lose the value of having it there.

**Comment by dcritch** [comment]
Works for me. If you can just add in the -s bit, we should be good to go.

**Comment by dcritch** [comment]
Great, thanks!

**Pull request merged**
