### PR TITLE
Proper exit codes and a few more changes

### PR DESCRIPTION
**Pull request by e-minguez**
* Proper exit codes and messages
* Added Mellanox firmware version checks
* Improved single script logic (info or check)
* Fixed usage message
* Added more stuff into the README
* Fixed MTU issue with wrong IFS
* Some code comments

### CODE REVIEW

**Comment by e-minguez** [comment]
@ptrnull @dcritch PTAL (check it in your cluster and report back before merging it 😅 )

**Comment by e-minguez** [comment]
I've pushed some minor nits :)

**Comment by dcritch** [comment]
tested and lgtm too. thanks!

**Pull request merged**
