### PR TITLE
Added support for byo debug image

### LINKED ISSUE #20: Wrong intel ID
https://docs.openshift.com/container-platform/4.6/networking/hardware_networks/about-sriov.html#supported-devices_about-sriov says:

```
Supported devices
OpenShift Container Platform supports the following Network Interface Card (NIC) models:

Intel XXV710 25GbE SFP28 with vendor ID 0x8086 and device ID 0x158b
```

### PR DESCRIPTION
**Pull request by e-minguez**
Also fix #20
Added some clarifications in the README

### CODE REVIEW

**Comment by dcritch** [comment]
I tested it with:
1/ support-tools:8.3 (exists)
2/ support-tools:somegarbage (does not)

Case 1 works fine so I assume would also be fine w/ a disconnected/internal registry.

But in case 2, I just get messages about BIOS/etc not found. Is there a way you can check if the image is valid if overridden so the error message is more accurate?

**Comment by e-minguez** [comment]
Good point. The thing is maybe the image is not available from the host running the script, only from the nodes. Let me figure out something

**Comment by dcritch** [comment]
might be just need to look at the return code or error message from the `oc debug` commands more closely:


```$ oc debug --image="${OCDEBUGIMAGE}" "${node}" -- chroot /host sh -c "cat /sys/class/dmi/id/bios_version" 

Creating debug namespace/openshift-debug-node-gglnv ...

Starting pod/node0cloudxanadu-debug ...

To use host binaries, run `chroot /host`



Removing debug pod ...

Removing debug namespace/openshift-debug-node-gglnv ...
error: Back-off pulling image "registry.redhat.io/rhel8/support-tools:404"

```

**Comment by e-minguez** [comment]
I've been looking into this but I've found that `oc debug` doesn't pass the error codes to the shell properly. If the command executed fails or if oc debug itself fails, the return code is always 1:

```
$ oc debug node/kni1-master-1.example.com  -- chroot /host sh -c "exit 3"
...
error: non-zero exit code from debug container
$ echo $?
1
```
vs
```
$ oc debug --image=it/doesnt/exits node/kni1-master-1.example.com  -- chroot /host sh -c "exit 3"
...
error: Back-off pulling image "it/doesnt/exits"
$ echo $?
1
```

**Comment by e-minguez** [comment]
I think I've managed to check the errors... do you mind to take a look again @dcritch ?

**Comment by dcritch** [comment]
Works for me. I could nit over why oc debug couldn't run, but its enough to point someone in the right direction :)

**Pull request merged**
