### PR TITLE
add --results-only mode

### PR DESCRIPTION
**Pull request by loganmc10**
This adds a new mode that silences the output from all the checks, and instead just prints the results from the checks, like this:

image

Once the user knows what checks are failing, they can see the output by running the specific check:
```
./openshift-checks.sh -s checks/alertmanager
```

Also, fix a typo in the spelling of OCUNKNOWN

### CODE REVIEW

**Comment by dcritch** [comment]
I think there is something a little funky with this one. A bunch of tests return FAIL, but running them manually shows no issue:
Screenshot from 2022-03-15 15-34-27

**Comment by loganmc10** [comment]
Yes correct, that is the issue the other PR fixed. I've rebased this one

**Comment by dcritch** [comment]
Sweet, looks slick. Thanks!

**Comment by dcritch** [comment]
Shoot, forgot... can update the readme to cover the new flag? New PR is fine

**Pull request merged**
