### PR TITLE
Added script to check nic firmware using ethtool

### PR DESCRIPTION
**Pull request by e-minguez**

### CODE REVIEW

**Comment by ptrnull** [comment]
/lgtm

```
./openshift-checks.sh -s info/ethtool-firmware-version
Using openshift-sriov-network-operator/rna1-vmaster-2:6443/kube:admin context
Checking NIC firmware version using ethtool (using oc debug, it can take a while)
node/rna1-master-0.*:
eno1 => 14.26.6000 (DEL2810000034)
eno2 => 14.26.6000 (DEL2810000034)
ens1f0 => 14.26.6000 (DEL2420110034)
ens1f0v2 => 14.26.6000 (DEL2420110034)
ens1f0v3 => 14.26.6000 (DEL2420110034)
ens1f0v4 => 14.26.6000 (DEL2420110034)
ens1f0v5 => 14.26.6000 (DEL2420110034)
ens1f0v6 => 14.26.6000 (DEL2420110034)
ens1f0v7 => 14.26.6000 (DEL2420110034)
ens1f1 => 14.26.6000 (DEL2420110034)
ens1f1v2 => 14.26.6000 (DEL2420110034)
ens1f1v3 => 14.26.6000 (DEL2420110034)
ens1f1v4 => 14.26.6000 (DEL2420110034)
ens1f1v5 => 14.26.6000 (DEL2420110034)
ens1f1v6 => 14.26.6000 (DEL2420110034)
ens1f1v7 => 14.26.6000 (DEL2420110034)
node/rna1-master-1*:
eno1 => 14.26.6000 (DEL2810000034)
eno2 => 14.26.6000 (DEL2810000034)
ens1f0 => 14.26.6000 (DEL2420110034)
ens1f0v2 => 14.26.6000 (DEL2420110034)
ens1f0v3 => 14.26.6000 (DEL2420110034)
ens1f0v4 => 14.26.6000 (DEL2420110034)
ens1f0v5 => 14.26.6000 (DEL2420110034)
ens1f0v6 => 14.26.6000 (DEL2420110034)
ens1f0v7 => 14.26.6000 (DEL2420110034)
ens1f1 => 14.26.6000 (DEL2420110034)
ens1f1v2 => 14.26.6000 (DEL2420110034)
ens1f1v3 => 14.26.6000 (DEL2420110034)
ens1f1v4 => 14.26.6000 (DEL2420110034)
ens1f1v5 => 14.26.6000 (DEL2420110034)
ens1f1v6 => 14.26.6000 (DEL2420110034)
ens1f1v7 => 14.26.6000 (DEL2420110034)
node/rna1-master-2.*:
eno1 => 14.26.6000 (DEL2810000034)
eno2 => 14.26.6000 (DEL2810000034)
ens1f0 => 14.26.6000 (DEL2420110034)
ens1f0v2 => 14.26.6000 (DEL2420110034)
ens1f0v3 => 14.26.6000 (DEL2420110034)
ens1f0v4 => 14.26.6000 (DEL2420110034)
ens1f0v5 => 14.26.6000 (DEL2420110034)
ens1f0v6 => 14.26.6000 (DEL2420110034)
ens1f0v7 => 14.26.6000 (DEL2420110034)
ens1f1 => 14.26.6000 (DEL2420110034)
ens1f1v2 => 14.26.6000 (DEL2420110034)
ens1f1v3 => 14.26.6000 (DEL2420110034)
ens1f1v4 => 14.26.6000 (DEL2420110034)
ens1f1v5 => 14.26.6000 (DEL2420110034)
ens1f1v6 => 14.26.6000 (DEL2420110034)
ens1f1v7 => 14.26.6000 (DEL2420110034)
node/rna1-vmaster-0:
enp1s0 => firmware-version: 
enp2s0 => firmware-version: 
node/rna1-vmaster-1:
enp1s0 => firmware-version: 
enp2s0 => firmware-version: 
node/rna1-vmaster-2:
enp1s0 => firmware-version: 
enp2s0 => firmware-version: 
No issues found
```

**Comment by dcritch** [comment]
me too.

do we still want to keep the mellanox and intel checks, or should we just leave it all to this?

**Comment by e-minguez** [comment]
> me too.
> 
> do we still want to keep the mellanox and intel checks, or should we just leave it all to this?

I'm leaning towards leaving all the scripts just in case... For instance, we didn't tested all the mellanox combinations (because we don't have the hardware), so we don't know if there are some nics that doesn't provide the firmware version via ethtool

Given said that, we can always delete the scripts and rollback the changes if needed /shrug :)

**Comment by dcritch** [comment]
The one advantage is that the ethtool script doesn't care about supported devices :)

**Pull request merged**
