### PR TITLE
feat: Remove temporary files on exit

### PR DESCRIPTION
**Pull request by iranzo**
Removes dangling tmpfiles on script exit

Built on top of #107 this commit only changes a few lines in the scripts

### CODE REVIEW

**Review by dcritch — COMMENTED** [review]
did something go funky w/ your PR? this one has the ocdebugorwait stuff in it as well

**Comment by iranzo** [comment]
> did something go funky w/ your PR? this one has the ocdebugorwait stuff in it as well

As mentioned, this was built on top of the other PR so this one list two commits, but once the other one is merged, this is just a few lines on top

**Review by dcritch — APPROVED** [review]
Ah, right. Thanks!

**Review by ptrnull — APPROVED** [review]
/lgtm thanks @iranzo

**Pull request merged**
