### PR TITLE
Emit error codes for checks execution

### LINKED ISSUE #62: [BUG] Checks with OC should be expanded
image

image

In both cases, we got RC 0, so the check should check ERRcode only but also output, affects lots of scripts in the repo

### PR DESCRIPTION
**Pull request by iranzo**
This PR is built on top of #61 , and includes some error code output for the scripts that might need to be adjusted using NAGIOS defaults for RC's

### CODE REVIEW

**Review by ptrnull — CHANGES_REQUESTED** [review]
@iranzo the introduction of the errorcodes has introduced an issue with the actual error management system, now the errors counter is not incremented anymore, looks like it's because before everything was executed in the same thread using source and now there are different executions of each script so the counter is lost:

With the update:
```
$ ./openshift-checks.sh -s checks/operators 
Using kube:admin context
Operators in Bad State (2):
image-registry                             4.4.5   False   False   True    163d
openshift-samples                          4.4.5   True    True    False   68s
No issues found
```
Before:
```
$ ./openshift-checks.sh -s checks/operators 
Using kube:admin context
Operators in Bad State (2):
image-registry                             4.4.5   False   False   True    163d
openshift-samples                          4.4.5   True    True    False   84s
Total issues found: 1
```

**Comment by iranzo** [comment]
> @iranzo the introduction of the errorcodes has introduced an issue with the actual error management system, now the errors counter is not incremented anymore, looks like it's because before everything was executed in the same thread using source and now there are different executions of each script so the counter is lost:
> 
> With the update:
> 
> ```
> $ ./openshift-checks.sh -s checks/operators 
> Using kube:admin context
> Operators in Bad State (2):
> image-registry                             4.4.5   False   False   True    163d
> openshift-samples                          4.4.5   True    True    False   68s
> No issues found
> ```
> 
> Before:
> 
> ```
> $ ./openshift-checks.sh -s checks/operators 
> Using kube:admin context
> Operators in Bad State (2):
> image-registry                             4.4.5   False   False   True    163d
> openshift-samples                          4.4.5   True    True    False   84s
> Total issues found: 1
> ```

Let me modify the execution about the counters

**Review by ptrnull — APPROVED** [review]
/lgtm

single test works fine:
```
$ ./openshift-checks.sh -s checks/operators 
Using kube:admin context
Operators in Bad State (1):
image-registry                             4.4.5   False   False   True    164d
Total issues found: 1
```

Complete execution also works fine:
```
NAMESPACE                  NAME                               READY   STATUS    RESTARTS   AGE
default                    test-deployment-69c79f84bb-rgb2n   0/1     Pending   0          59d
openshift-image-registry   image-registry-74b5997554-lph4r    0/1     Pending   0          149d
openshift-image-registry   image-registry-b847c4bb4-c7t8b     0/1     Pending   0          149d
Operators in Bad State (2):
image-registry                             4.4.5   False   False   True    164d
openshift-samples                          4.4.5   True    True    False   2m33s
Total issues found: 5

```

**Comment by iranzo** [comment]
Rebased on top of main to reduce number of visible changes

**Comment by dcritch** [comment]
thanks Pablo!

**Pull request merged**
